### ISSUE TITLE
No return statement in function -> youtube-api-analysis/Sample_project_youtube_videos_EDA.ipynb

### ISSUE THREAD

**Issue by sushaaant20** [thu-vu92/youtube-api-analysis#1]
def get_video_details(youtube, video_ids) function does not return anyhting.
I think it is supposed to return - **return pd.DataFrame(all_video_info)**
![return](https://user-images.githubusercontent.com/41162773/176003113-8281bd20-2772-417f-b8f2-758b549b9d51.png)

**Comment by thu-vu92** [comment]
Thank you! I've fixed it :).
